/*
 * Copyright 2026 LiveKit
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <livekit/data_track_schema.h>
#include <livekit/livekit.h>

#include <atomic>
#include <chrono>
#include <csignal>
#include <cstdint>
#include <cstdlib>
#include <ctime>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>

namespace schema_mcap {

inline constexpr char kDefaultLiveKitUrl[] = "ws://localhost:7880";
inline constexpr char kDataTrackName[] = "pointcloud-json";
inline constexpr char kSchemaName[] = "foxglove.PointCloud";
inline constexpr char kMcapChannelTopic[] = "/pointcloud";
inline constexpr int kPointCloudFrameCount = 50;
inline constexpr int kPointCloudPointsPerFrame = 512;
inline constexpr int kDefaultRecorderFrameCount = kPointCloudFrameCount;

// Canonical Foxglove JSON schema from:
// https://github.com/foxglove/foxglove-sdk/blob/main/schemas/jsonschema/PointCloud.json
inline constexpr char kPointCloudJsonSchema[] = R"json({
  "title": "foxglove.PointCloud",
  "description": "A collection of N-dimensional points, which may contain additional fields with information like normals, intensity, etc.",
  "$comment": "Generated by https://github.com/foxglove/foxglove-sdk",
  "type": "object",
  "properties": {
    "timestamp": {
      "type": "object",
      "title": "time",
      "properties": {
        "sec": {
          "type": "integer",
          "minimum": 0
        },
        "nsec": {
          "type": "integer",
          "minimum": 0,
          "maximum": 999999999
        }
      },
      "description": "Timestamp of point cloud"
    },
    "frame_id": {
      "type": "string",
      "description": "Frame of reference"
    },
    "pose": {
      "title": "foxglove.Pose",
      "description": "The origin of the point cloud relative to the frame of reference",
      "type": "object",
      "properties": {
        "position": {
          "title": "foxglove.Vector3",
          "description": "Point denoting position in 3D space",
          "type": "object",
          "properties": {
            "x": {
              "type": "number",
              "description": "x component"
            },
            "y": {
              "type": "number",
              "description": "y component"
            },
            "z": {
              "type": "number",
              "description": "z component"
            }
          },
          "required": ["x", "y", "z"]
        },
        "orientation": {
          "title": "foxglove.Quaternion",
          "description": "Quaternion denoting orientation in 3D space",
          "type": "object",
          "properties": {
            "x": {
              "type": "number",
              "description": "x value"
            },
            "y": {
              "type": "number",
              "description": "y value"
            },
            "z": {
              "type": "number",
              "description": "z value"
            },
            "w": {
              "type": "number",
              "description": "w value"
            }
          },
          "required": ["x", "y", "z", "w"]
        }
      },
      "required": ["position", "orientation"]
    },
    "point_stride": {
      "type": "integer",
      "minimum": 0,
      "description": "Number of bytes between points in the `data`"
    },
    "fields": {
      "type": "array",
      "items": {
        "title": "foxglove.PackedElementField",
        "description": "A field present within each element in a byte array of packed elements.",
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the field"
          },
          "offset": {
            "type": "integer",
            "minimum": 0,
            "description": "Byte offset from start of data buffer"
          },
          "type": {
            "title": "foxglove.NumericType",
            "description": "Type of data in the field. Integers are stored using little-endian byte order.",
            "oneOf": [
              {"title": "UNKNOWN", "const": 0, "description": "Unknown numeric type"},
              {"title": "UINT8", "const": 1, "description": "Unsigned 8-bit integer"},
              {"title": "INT8", "const": 2, "description": "Signed 8-bit integer"},
              {"title": "UINT16", "const": 3, "description": "Unsigned 16-bit integer"},
              {"title": "INT16", "const": 4, "description": "Signed 16-bit integer"},
              {"title": "UINT32", "const": 5, "description": "Unsigned 32-bit integer"},
              {"title": "INT32", "const": 6, "description": "Signed 32-bit integer"},
              {"title": "FLOAT32", "const": 7, "description": "32-bit floating-point number"},
              {"title": "FLOAT64", "const": 8, "description": "64-bit floating-point number"}
            ]
          }
        },
        "required": ["name", "offset", "type"]
      },
      "description": "Fields in `data`. At least 2 coordinate fields from `x`, `y`, and `z` are required for each point's position; `red`, `green`, `blue`, and `alpha` are optional for customizing each point's color."
    },
    "data": {
      "type": "string",
      "contentEncoding": "base64",
      "description": "Point data, interpreted using `fields`"
    }
  },
  "required": ["timestamp", "frame_id", "pose", "point_stride", "fields", "data"]
})json";

inline std::atomic<bool> g_running{true};

inline void handleSignal(int) { g_running.store(false); }

inline void installSignalHandlers() {
  std::signal(SIGINT, handleSignal);
#ifdef SIGTERM
  std::signal(SIGTERM, handleSignal);
#endif
}

inline bool isRunning() { return g_running.load(std::memory_order_relaxed); }

inline std::string getenvOrEmpty(const char* name) {
  const char* value = std::getenv(name);
  return value ? std::string(value) : std::string{};
}

inline std::uint64_t nowEpochUs() {
  return static_cast<std::uint64_t>(
      std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::system_clock::now().time_since_epoch())
          .count());
}

inline std::uint64_t nowEpochNs() {
  return static_cast<std::uint64_t>(
      std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::system_clock::now().time_since_epoch())
          .count());
}

inline std::string localTimestampForFilename() {
  const std::time_t now = std::time(nullptr);
  std::tm local_time{};
#ifdef _WIN32
  localtime_s(&local_time, &now);
#else
  localtime_r(&now, &local_time);
#endif

  std::ostringstream out;
  out << std::put_time(&local_time, "%Y%m%d_%H%M%S");
  return out.str();
}

inline std::vector<std::uint8_t> toPayload(const std::string& text) {
  return std::vector<std::uint8_t>(text.begin(), text.end());
}

inline livekit::DataTrackSchemaId pointCloudSchemaId() {
  return livekit::DataTrackSchemaId{kSchemaName, livekit::DataTrackSchemaEncoding::JsonSchema};
}

inline std::string schemaEncodingName(const livekit::DataTrackSchemaEncoding& encoding) {
  if (encoding.isCustom()) {
    return encoding.customIdentifier();
  }

  switch (encoding.wellKnown()) {
    case livekit::DataTrackSchemaEncoding::Protobuf:
      return "protobuf";
    case livekit::DataTrackSchemaEncoding::Flatbuffer:
      return "flatbuffer";
    case livekit::DataTrackSchemaEncoding::Ros1Msg:
      return "ros1msg";
    case livekit::DataTrackSchemaEncoding::Ros2Msg:
      return "ros2msg";
    case livekit::DataTrackSchemaEncoding::Ros2Idl:
      return "ros2idl";
    case livekit::DataTrackSchemaEncoding::OmgIdl:
      return "omgidl";
    case livekit::DataTrackSchemaEncoding::JsonSchema:
      return "jsonschema";
    case livekit::DataTrackSchemaEncoding::Other:
      return "unknown";
  }

  return "unknown";
}

inline std::string frameEncodingName(const livekit::DataTrackFrameEncoding& encoding) {
  if (encoding.isCustom()) {
    return encoding.customIdentifier();
  }

  switch (encoding.wellKnown()) {
    case livekit::DataTrackFrameEncoding::Ros1:
      return "ros1";
    case livekit::DataTrackFrameEncoding::Cdr:
      return "cdr";
    case livekit::DataTrackFrameEncoding::Protobuf:
      return "protobuf";
    case livekit::DataTrackFrameEncoding::Flatbuffer:
      return "flatbuffer";
    case livekit::DataTrackFrameEncoding::Cbor:
      return "cbor";
    case livekit::DataTrackFrameEncoding::Msgpack:
      return "msgpack";
    case livekit::DataTrackFrameEncoding::Json:
      return "json";
    case livekit::DataTrackFrameEncoding::Other:
      return "unknown";
  }

  return "unknown";
}

template <typename ErrorT>
std::string describeDataTrackError(const ErrorT& error) {
  return "code=" + std::to_string(static_cast<std::uint32_t>(error.code)) + " message=" + error.message;
}

} // namespace schema_mcap
